# Makefile for unit tests

all: 

clean:
	$(info   *************** tests clean ***************)

install:
	$(info   *************** install checkpoint ***************)

unit_tests:
	$(info   *************** make all unit tests ***************)

check: all

.PHONY: all unit_tests clean
