.\" Manpage for engine.

.TH man 6 "17 Apr 2021" "0.2.8" "engine man page"
.SH NAME
engine \- Graphics Render Engine 
.SH SYNOPSIS 
engine [options]
.SH DESCRIPTION
Engine is short for "graphics rendering enigne". It is a multi-platform rendering backend.
The application Marley is a suite of console emulators plus a launcher frontend.
In version 0.2.8, the bundle is comprised of GBA, GBC, NES, SNES, PS1, Sega Genesis, 
and Sega Saturn provided by Mednafen.
Visit https://github.com/beaumanvienna/gfxRenderEngine for more information.

.SH AUTHOR
Team Engine. To contact us, open an issues ticket on https://github.com/beaumanvienna/gfxRenderEngine. Pull requests are welcome!
