.\" Manpage for engine.

.TH man 6 "17 Apr 2021" "0.0.1" "engine man page"
.SH NAME
engine \- Graphics Render Engine 
.SH SYNOPSIS 
engine [options]
.SH DESCRIPTION
Engine is short for "graphics rendering enigne". It is a multi-platform rendering backend.
Visit https://github.com/beaumanvienna/gfxRenderEngine for more information.
.SH OPTIONS
  --version             : print version
  --fullscreen, -f      : start in fullscreen mode
  
.SH SEE ALSO

.SH BUGS

.SH AUTHOR
Team Engine. To contact us, open an issues ticket on https://github.com/beaumanvienna/gfxRenderEngine. Pull requests are welcome!
