#pragma once

// IMAGES
#define I_CHECKEDBOX 0
#define I_GRID 1
#define I_UP_DIRECTORY_R 2
#define I_FOLDER 3
#define I_BACK_R 4
#define I_DISK_EMPTY 5
#define I_WHITE 6
#define I_LOGO_DOLPHIN 7
#define I_FOLDER_R 8
#define I_HOME_R 9
#define I_BEACH 10
#define I_LOGO_MEDNAFEN 11
#define I_HORN 12
#define I_LOGO_PPSSPP 13
#define I_BACK 14
#define I_WALKUP 15
#define I_LOGO_PCSX2 16
#define I_WALK 17
#define I_LOGO_MUPEN 18
#define I_ENGINE 19
#define I_DISK_LOAD_R 20
#define I_BARREL 21
#define I_DISK_SAVE 22
#define I_GRID_R 23
#define I_SIGN3_R 24
#define I_DISK_SAVE_R 25
#define I_OFF 26
#define I_PS3_CONTROLLER 27
#define I_UP_DIRECTORY 28
#define I_WALKDOWN 29
#define I_LINES_R 30
#define I_OFF_R 31
#define I_DROP_SHADOW 32
#define I_GEAR 33
#define I_GEAR_R 34
#define I_SQUARE 35
#define I_LINES 36
#define I_SIGN_R 37
#define I_MARLEYLOGO 38
#define I_STAR 39
#define I_CIRCLE 40
#define I_HOME 41
#define I_DISK_LOAD 42
#define I_SIGN2_R 43
#define I_CONTROLLER 44
#define I_TAB_R 45
#define I_CLOUDS 46
