#pragma once

// IMAGES
#define I_DISK_LOAD 0
#define I_WHITE 1
#define I_DISK_SAVE 2
#define I_LOGO_PPSSPP 3
#define I_HORN 4
#define I_LINES_R 5
#define I_BACK 6
#define I_WALKUP 7
#define I_DISK_SAVE_R 8
#define I_GEAR_R 9
#define I_BACK_R 10
#define I_UP_DIRECTORY_R 11
#define I_CHECKEDBOX 12
#define I_LOGO_DOLPHIN 13
#define I_HOME_R 14
#define I_LOGO_MEDNAFEN 15
#define I_WALK 16
#define I_TAB_R 17
#define I_BEACH 18
#define I_ENGINE 19
#define I_MARLEYLOGO 20
#define I_CIRCLE 21
#define I_DROP_SHADOW 22
#define I_GEAR 23
#define I_DISK_EMPTY 24
#define I_LINES 25
#define I_BARREL 26
#define I_GRID_R 27
#define I_OFF 28
#define I_SIGN2_R 29
#define I_PS3_CONTROLLER 30
#define I_FOLDER 31
#define I_SIGN_R 32
#define I_LOGO_PCSX2 33
#define I_FOLDER_R 34
#define I_HOME 35
#define I_LOGO_MUPEN 36
#define I_GRID 37
#define I_OFF_R 38
#define I_DISK_LOAD_R 39
#define I_WALKDOWN 40
#define I_SQUARE 41
#define I_CONTROLLER 42
#define I_UP_DIRECTORY 43
#define I_STAR 44
#define I_CLOUDS 45
