// Header generated by atlastool from atlasscript.txt (hrydgard@gmail.com)
#include "atlasPPSSPP.h"

#pragma once

// IMAGES_ui
#define I_HORN 0
#define I_WALK 1
#define I_WALKDOWN 2
#define I_WALKUP 3
#define I_LINES_R 4
#define I_TAB_R 5
#define I_GRID_R 6
#define I_GEAR_R 7
#define I_OFF_R 8
#define I_HOME_R 9
#define I_BACK_R 10
#define I_BARREL 11
#define I_CLOUDS 12
#define I_BEACH 13
#define I_ENGINE 14
#define I_WHITE 15
#define I_CONTROLLER 16
#define I_STAR 17


extern const Atlas ui_atlas;
extern const AtlasImage ui_images[18];
