// Header generated by atlastool from atlasscript.txt (hrydgard@gmail.com)
#include "atlasPPSSPP.h"

#pragma once

// IMAGES_ui
#define I_HORN 0
#define I_WALK 1
#define I_WALKDOWN 2
#define I_WALKUP 3
#define I_GEAR 4
#define I_OFF 5
#define I_HOME 6
#define I_BACK 7
#define I_LINES_R 8
#define I_TAB_R 9
#define I_GRID_R 10
#define I_UP_DIRECTORY_R 11
#define I_FOLDER_R 12
#define I_GEAR_R 13
#define I_OFF_R 14
#define I_HOME_R 15
#define I_BACK_R 16
#define I_BARREL 17
#define I_DOLPHIN 18
#define I_CLOUDS 19
#define I_BEACH 20


extern const Atlas ui_atlas;
extern const AtlasImage ui_images[21];
