// Header generated by atlastool from atlasscript.txt (hrydgard@gmail.com)

#pragma once

// IMAGES_ui
#define I_SOLIDWHITE 0
#define I_CROSS 1
#define I_CIRCLE 2
#define I_SQUARE 3
#define I_TRIANGLE 4
#define I_SELECT 5
#define I_START 6
#define I_ARROW 7
#define I_DIR 8
#define I_ROUND 9
#define I_RECT 10
#define I_STICK 11
#define I_STICK_BG 12
#define I_SHOULDER 13
#define I_DIR_LINE 14
#define I_ROUND_LINE 15
#define I_RECT_LINE 16
#define I_SHOULDER_LINE 17
#define I_STICK_LINE 18
#define I_STICK_BG_LINE 19
#define I_CHECKEDBOX 20
#define I_BG 21
#define I_L 22
#define I_R 23
#define I_DROP_SHADOW 24
#define I_LINES 25
#define I_GRID 26
#define I_LOGO 27
#define I_ICON 28
#define I_UP_DIRECTORY 29
#define I_FOLDER 30
#define I_GEAR 31
#define I_OFF 32
#define I_HOME 33
#define I_BACK 34
#define I_LINES_R 35
#define I_TAB_R 36
#define I_GRID_R 37
#define I_UP_DIRECTORY_R 38
#define I_FOLDER_R 39
#define I_GEAR_R 40
#define I_OFF_R 41
#define I_HOME_R 42
#define I_BACK_R 43
#define I_BARREL 44
#define I_DOLPHIN 45
#define I_CLOUDS 46
#define I_BEACH 47
#define I_CTRL_PS3 48
#define I_CTRL_PS4 49
#define I_CTRL_SNES 50
#define I_CTRL_WII 51
#define I_CTRL_XB 52
#define I_CTRL_GENERIC 53
#define I_CTRL_NOT_FOUND 54
#define I_1 55
#define I_2 56
#define I_3 57
#define I_4 58
#define I_5 59
#define I_6 60
#define I_PSP_DISPLAY 61
#define I_FLAG_JP 62
#define I_FLAG_US 63
#define I_FLAG_EU 64
#define I_FLAG_HK 65
#define I_FLAG_AS 66
#define I_FLAG_KO 67
#define I_HORN 68
#define I_WALK 69
#define I_WALKDOWN 70
#define I_WALKUP 71


extern const Atlas ui_atlas;
extern const AtlasImage ui_images[72];
