name: 😍 Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive -j $(getconf _NPROCESSORS_ONLN)

    - name: Setup premake
      uses: abel0b/setup-premake@v1

    - name: premake
      run: premake5 vs2019
    
    - name: MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: compile
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:TrackFileAccess=false /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ matrix.platform }} gfxRenderEngine.sln

    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "download-artifacts" -ItemType "directory"
      shell: powershell

     - name: copy compile artifacts
       run: Copy 'bin/' '${{ github.workspace }}/download-artifacts'
       shell: powershell

     - name: upload artifacts
       uses: actions/upload-artifact@v2
       with:
         path: ${{ github.workspace }}/download-artifacts
         name: engine-windows
